// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oonaetktfrwnfppgpccj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9vbmFldGt0ZnJ3bmZwcGdwY2NqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEzODEzNTAsImV4cCI6MjA4Njk1NzM1MH0.0RDUipcs6slSfNCyFw358-yKLhEp21WotJ8VwsavRxY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});